services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=okaerinasai
      - MYSQL_ROOT_PASSWORD=okaerinasai
    ports:
      - 3306:3306
volumes:
  mysql_data:
    driver: local