home-cooldown: 5.0
warp-cooldown: 10.0
particle: ENCHANT
particle-amount: 20
default-home: home
default-warp: warp
db-url: default_db_url
db-user: default_db_root
db-password: default_db_password
arrive-text: Okaerinasai, goshujin-sama!!!